:sectnums:
:sectnumlevels: 6
:toc: left
:toclevels: 2
:toc-title: Оглавление


Для нового приложения необходимо спроектировать систему управления контролем доступа на основе ролей.

Система должна принимать в качестве входных параметров

* id пользователя
* id ресурса

Cистема не контролирует id ресурса, он может быть произвольным.


Система должна отдавать запрашивающей стороне, какие операции пользователь с таким id может проводить над ресурсом с указанным id (например:  edit, delete и т.д.)


Необходимый функционал:

. В системе должна быть предусмотрена возможность создания/удаления/изменения групп пользователей и назначение ролей на такие группы пользователей
. В системе также должна быть предусмотрена возможность добавления и удаления пользователей из системы, а также изменения их метаданных
. В системе должна быть предусмотрена возможность создания / удаления / изменения ролей, а также добавления в них полномочий. Способ реализации связки полномочий с ресурсами - на усмотрение реализующего
. В системе должна быть предусмотрена возможность создания / удаления / изменения полномочий

Задание:

* Спроектировать REST API такой системы (в формате openapi / raml)
* Спроектировать структуру данных такой системы (er диаграмма, база данных - на усмотрение реализующего)
* Для MVP не требуется аутентификация пользователей, она выполняется в сторонней системы. На вход дается used id для которого не требуется проводить процедуру аутентификации
* Задание со звездочкой: добавить модуль аутентификации. Способ аутентификации - на усмотрение реализующего (но минимум oAuth2, flow - на усмотрение реализующего)
* Задание с двумя звездочками: добавить возможность social login
