:sectnums:
:sectnumlevels: 6
:toc: left
:toclevels: 3
:toc-title: Оглавление

== Логика работы основного функционала системы

Уровень логики - уровень реализации основного фукционала системы, который может потом быть использован как самой системой,
так и выставлен в виде API или сервисов для использования системами - потребителями.

Основной фунцкионал:

- добавление пользователя
- удаление пользователя

- создание группы пользователей
- удаление группы пользователей
- изменение состава участников группы пользователей

- назначение роли на группу
- удаление роли у группы

- добавление полномочия в роль
- удаление полномочия из роли

В ходе выполнения могут случаться как ошибки бизнес процесса, так и технические ошибки. Все ошибки необходимо упаковывать в единый формат исключений.
Ожидается, что все бизнес ошибки будут иметь коды, задаваемые в файле настроек, и тексты (например это будет yml).
Тексты биснес ошибок прописаны в описании функций. Описание структуры ошибки в файле <<./API-Templates/exceptions.adoc,exceptions>>.


=== Сервисы

==== (Вспомогательная) Выдача нового идентификатора GetNewIDService

Функция выдачи нового идентификтора объекта - определяет новый ID для переданного типа сущности.
Функционая должна создавать уникальные идентификаторы для каждой сущьности одного типа.

Функция должна быть переопределена для:

* пользователя (выдача нового id для сущности Person)
* группы (выдача нового id для сущности Group)
* роли (выдача нового id для сущности Role)
* права (выдача нового id для сущности Permission)
* ресурса (выдача нового id для сущности Sourse)

В случае невозможности выдачи нового id вернуть ошибку "Не удалось создать новый идентификатор для {тип сущности}"

==== (Вспомогательная) Проверка объекта по ID CheckObjectByIDService

Функция проверки существования объекта с заданным идентификатором.
Функция должна быть переопределена для:

* пользователя (проверка наличия Person по заданному id)
* группы (проверка наличия Group по заданному id)
* роли (проверка наличия Role по заданному id)
* права (проверка наличия Permission по заданному id)
* ресурса (проверка наличия Sourse по заданному id)

===== Входящие параметры
|===
|*Параметр*             |*Формат*                 |*Описание*
| sourse_id             | int                     | Идентификатор ресурса
|===

TODO  Тут не хватает логики чтобы отличить тип ресурса от объекта

===== Выходящие параметры

|===
|*Параметр*             |*Формат*                 |*Описание*
|                       | bool
a|* true - произошла ошибка, обектов нет или более 1, сформировать ошибку "Объект {id} не найден или найдено более 1 экземпляра"
  * false - ошибок нет, объект существует в 1 экземпляре
|===

===== Алгоритм

. Для переданного типа ресурса необходимо проверить наличие объекта с этим ресурсом в соотвертсвующей сущьности.
 Вернуть 0 если объект существует, 1 есть объекта нет

==== Создание пользователя CreatePersonServise

===== Входящие параметры
|===
|*Параметр*             |*Формат*                 |*Описание*
|name                   | string(255)             | Имя пользователя
|===

===== Выходящие параметры
|===
|*Параметр*             |*Формат*                 |*Описание*
| id                    | int                     | Идентификатор созданого пользователя
|===

TODO: должна система хранить инфо про удаленных пользователей или должна помечать их неактивными?
Если должна хранить удаленных, тогда нужно расширение атрибутов Person, а только что созданных помечать активными.

===== Алгоритм

. Получить новый идентификатор GetNewIDService()
. Сохранить новый экземпляр Person с полученным идентификатором

==== Удаление пользователя RemovePersonServise

===== Входящие параметры
|===
|*Параметр*             |*Формат*             |*Описание*
| id                    | int                 | идентификатор пользователя
|===

===== Выходящие параметры

Пустой ответ - пользователь удален

===== Алгоритм

. Проверить существование удаляемого объекта CheckObjectByID
- если 1 - вывести ошибку ("Не удалось удалить пользователя {id}. Пользователь не найден")
- если 0 - выбрать объекты ListPersonsInGroup, удалить их (удаление связей), удалить экземпляр Person
. После удаления вызвать CheckObjectByID, если 1 - завершить работу (вернуть пустой ответ), если 0 - тогда вернуть ошибку "Не удалось удалить пользователя {id}"

==== Создание группы пользователей RemoveGroupOfPersonsServise

===== Входящие параметры
|===
|*Параметр*             |*Формат*                 |*Описание*
| name                  | string(255)             | Имя группы
|===

===== Выходящие параметры
|===
|*Параметр*             |*Формат*                 |*Описание*
| id                    | int                     | идентификатор группы
|===

===== Алгоритм
. Получить новый идентификатор группы GetNewIDService
. Сохранить новый экземпляр Group
. CheckObjectByID для только что созданной группы, если 0 (ошибок нет, объект есть в единственном экземпляре) то вернуть id) и завершить работу
. Если результат предыдущего шага 1, тогда вернуть ошибку "Не удалось создать группу {name}"


==== Удаление группы пользователей CreateGroupOfPersonsServise

===== Входящие параметры
|===
|*Параметр*             |*Формат*                 |*Описание*
| name                  | string(255)             | Имя группы
|===

===== Выходящие параметры
Пустой ответ - группа удалена

===== Алгоритм

. Проверить существование удаляемого объекта CheckObjectByID
- если 1 - вывести ошибку ("Не удалось удалить группу {id}. Группа не найдена")
- если 0 - выбрать объекты ListPersonsInGroup, удалить их (удаление связей), выбрать объекты ListRoles, удалить их (удаление связей), удалить экземпляр Group
. После удаления вызвать CheckObjectByID, если 1 - завершить работу (вернуть пустой ответ), если 0 - тогда вернуть ошибку "Не удалось удалить группу {id}."


====  Изменение состава участников группы пользователей EditPersonsInGroupServise

TODO: поговорить с разработкой, возможно разнести на 2 процесса - добавление и удаление. +
TODO: есть ли пользователи/процессы, которые имеют право только добавлять или только удалять?

===== Входящие параметры
|===
|*Параметр*            |*Формат*                 |*Описание*
| group_id             | int                     | идентификатор группы
a| list <structure ChangeStatusPersonInGroup>
----
1: person_id
2: operation
3: action
----
|
1: int +
2: int +
3: string ("add" , "remove")
| Идентификатор группы +
идентификатор пользователя +
дейстивие (добавление, удаление)
|===

===== Выходящие параметры
|===
|*Параметр*            |*Формат*                 |*Описание*
|result                |varchar(20)              | результат выполнения
|errors                |list <struct Error>      | список ошибок
|===

* статус полностью или частично удалось выполнить,
* массив ошибок при частично выполненом
* TODO: кроме массива ошибок что удобнее вывести для фиксации неуспешного результата?  id ? или логов с ошибками достаточно? кто будет править эти ошибки?


===== Алгоритм

. Проверить существование группы CheckObjectByID
- если 1 - вывести ошибку ("Не удалось удалить группу {id}. Группа не найдена")

Для каждого экземпляра ChangeStatusPersonInGroup

. Проверить существование пользователя CheckObjectByID
- если 1 - вывести ошибку ("Не удалось найти пользователя {id}. Изменени настроек групп пользователя не выполнено.")
. Проверить наличие объекта ListPersonsInGroup с group_id и person_id.
- если связка есть и действие  `add`, тогда сформировать ошибку "Невозможно добавить пользователя {person_id} в группу {group_id}: пользователь уже есть в группе".
- если связка отсутствует и действие `remove`, тогда сформировать ошибку "Невозможно удалить пользователя {person_id} из группы {group_id}: пользователя нет в группе"
. Добавить / удалить необходимую связку

Если все удалось выполнить вернуть result -  "success"
Если все не удалось выполнить вернуть result -  "fail", список ошибок
Если все не удалось выполнить вернуть result -  "partFail", список ошибок

==== (Вспомогательная) Проверка наличия роли у группы CheckRoleGroupServise

===== Входные параметры

|===
|*Параметр*             |*Формат*                 |*Описание*
| id_group              | int                     | идентификатор группы
| id_role               | int                     | идентификатор пользователя
|===

===== Выходные параметры
1 - роль у группы есть
0 - роли у группы нет


===== Алгоритм
. Проверить существование группы CheckObjectByID, иначе ошибка.
. Проверить существование роли CheckObjectByID, иначе ошибка.
. Проверить наличие объекта ListRoles с id_group и id_role, если есть вернуть 1 , если нет - 0


==== Назначение роли на группу AddRoleInGroupServise

===== Входные параметры

|===
|*Параметр*             |*Формат*                 |*Описание*
| id_group              | int                     | идентификатор группы
| id_role               | int                     | идентификатор пользователя
|===

===== Выходные параметры

===== Алгоритм

.  Проверить наличие роли у группы CheckRoleGroup
если есть  - ошибка, "Не удалось добавить роль {id_role} группе {id_group}. Роль уже назначена"
если нет  - добавить

==== Удаление роли у группы RemoveRoleFromGroupServise

===== Входные параметры

|===
|*Параметр*             |*Формат*                 |*Описание*
| id_group              | int                     | идентификатор группы
| id_role               | int                     | идентификатор пользователя
|===

===== Выходные параметры
пусто - удалено успешно

===== Алгоритм

. Проверить наличие роли у группы CheckRoleGroup
если нет  - ошибка, "Не удалось удалить роль {id_role} у группы {id_group}. Роль не назначена на группу."
если нет  - удалить


==== (Вспомогательная) Проверка наличия полномочия у роли CheckPermissionRoleService

===== Входные параметры

|===
|*Параметр*             |*Формат*                 |*Описание*
| id_role               | int                     | идентификатор роли
| id_sourse             | int                     | идентификатор ресурса
| activity              | varchar(255)            | полномочие
|===

===== Выходные параметры
1 - есть
0 - нет

===== Алгоритм

. Проверить наличие роли CheckObjectByID
. Проверить наличие права в Permission с для ресурса id_sourse, запомнить его PermissionID
. Проверить наличие id_role, PermissionID в ListPermissions, если есть вернуть 1, иначе 0


==== Добавление полномочия в роль AddPermissonToRole

===== Входные параметры

|===
|*Параметр*             |*Формат*                 |*Описание*
| id_role               | int                     | идентификатор роли
| id_sourse             | int                     | идентификатор ресурса
| activity              | varchar(255)            | полномочие
|===

===== Выходные параметры

пусто - полномочие добавлено

===== Алгоритм

. Проверить наличие полномочия у роли CheckPermissionRoleService
- если есть вернуть ошибку "Невозможно добавить полномочие {activity} для ресурса {id_sourse} в роль {id_role}.  ПОлномочие уже существует. "
- если нет, тогда добавить в ListPermissions полномочие

====  Удаление полномочия из роли RemovePermissonFromRole

===== Входные параметры

|===
|*Параметр*             |*Формат*                 |*Описание*
| id_role               | int                     | идентификатор роли
| id_sourse             | int                     | идентификатор ресурса
| activity              | varchar(255)            | полномочие
|===

===== Выходные параметры

пусто - полномочие удалено

===== Алгоритм
. Проверить наличие полномочия у роли CheckPermissionRoleService
- если нет вернуть ошибку "Невозможно удалить полномочие {activity} для ресурса {id_sourse} из роли {id_role}. Полномочие отсутствует. "
- если есть, тогда удалить в ListPermissions полномочие

==== Формирование списка возможных операций пользователя над ресурсом getPersonPermissionsService

Примечание: Этот сервис будет вызываться API getPersonPermissions

Сервис формирования списка возможных операций пользователя над ресурсом

===== Входные параметры

|===
|*Параметр*             |*Формат*                 |*Описание*
| id_person             | int                     | идентификатор пользователя
| id_sourse             | int                     | идентификатор ресурса
|===

===== Выходные параметры

|===
|*Параметр*             |*Формат*                 |*Описание*
| id_person             | int                     | идентификатор пользователя
| list<actions>         |                         | список прав
|===

===== Алгоритм

Для формирования результата необходимо сделать запрос к БД (TODO: описать место хранения кредов к БД)

. вычисление групп пользователя (возможная ошибка: Пользователь {id_person} не состоит ни в одной группе)
. составление списка ролей всех групп, исключая повторения (возможная ошибка: Список ролей групп пользователя {id_person} пуст)
. формирование списка прав (возможная ошибка: Список прав групп пользотеля {id_person} пуст)
. фильтрация пермишенов по ресурсу (возможная ошибка: Список прав групп пользотеля {id_person} пуст для ресурса {id_sourse})
. удаление дибликатов (возможная ошибка: Список прав групп пользотеля {id_person} пуст для ресурса {id_sourse})
. формирование результата (возможная ошибка: Список прав групп пользотеля {id_person} пуст для ресурса {id_sourse})

Примечание: при наличии схемы БД тут были бы описаны маппинги на БД, но я ограниличать указанием сущностей

Примечание Все сервисы, с выставленным API или нет следует описать тут, конечно с делением на домены. Отдельно сервисы работы с группами, отдельно с ролями, и тд)