:sectnums:
:sectnumlevels: 6
:toc: left
:toclevels: 2
:toc-title: Оглавление

== Логика работы основного функционала системы.

Уровень логики - уровень реализации основного фукционала системы, который может потом быть использован как самой системой, так и выставлен в виде API или сервисов для
использования системами - потребителями.


Основной фунцкионал:

- добавление пользователя
- удаление пользователя

- создание группы пользователей
- изменение группы пользователей
- удаление группы пользователей


- назначение роли на группу
- удаление роли у группы пользователей
- добавление полномочия в роль
- удаление полномочия из роли

В ходе выполнения могут случаться как ошибки бизнес процесса, так и технические ошибки. Все ошибки необходимо упаковывать в единый формат исключений.
Ожидается, что все бизнес ошибки будут иметь коды, задаваемые в файле настроек, и тексты (например это будет yml).
Тексты биснес ошибок прописыны в описании функций. Описание структуры ошибки в файле <<solutions/API-Templates/exeptions.adoc,exeptions>>.


=== Вспомогательные функции

==== Выдача нового идентификатора GetNewID()

Функция выдачи нового идентификтора объекта - определяет новый ID для выбранной сущьности.
Функция должна быть переопределена для:

* пользователя (выдача нового id для сущьности Person)
* группы (выдача нового id для сущьности Group)
* роли (выдача нового id для сущьности Role)
* права (выдача нового id для сущьности Permission)
* ресурса (выдача нового id для сущьности Sourse)

Идентификатор новой сущьности уникален для каждой сущьности,
является ключом в соответствующей таблице БД.

В случае невозможности выдачи нового id вернуть ошибку "Не удалось создать новый идентивикатор для {тип сущьности}"

====  Проверка объекта по ID CheckObjectByID

Функция проверки существования объекта с данным идентификатором.
Функция должна быть переопределена для:

* пользователя  (выдача нового id для сущьности Person)
* группы (выдача нового id для сущьности Group)
* роли (выдача нового id для сущьности Role)
* права (выдача нового id для сущьности Permission)
* ресурса (выдача нового id для сущьности Sourse)

===== Входящие параметры
|===
|*Параметр*             |*Формат*                 |*Описание*
| id                    | int                     | Идентификатор ресурса
|===

===== Выходящие параметры

|===
|*Параметр*             |*Формат*                 |*Описание*
|                       | bool
a|* true - произошла ошибка, обектов нет или более 1, сформировать ошибку "Объект {id} не найден или найдено более 1 экземпляра"
  * false - ошибок нет, объект существует в 1 экземпляре
|===


==== Возвращает Id объекта по его имени GetIDByName

Замечание:  не считаю верным выход во вне системы идентификаторов объектов, внутренних сущьностей системы.
Эта функция задумана для перевода обращений по имени объекта на обращение по Id, пример стороннне приложение указывает что запрос идет пермишенов у "IvanovaMaria", не зная его id

TODO использовать это, и API переписать, убрать обращения по id

TODO Опечаток стало много, пора спать.

=== Основные функции системы

==== Создание пользователя

===== Входящие параметры
|===
|*Параметр*             |*Формат*                 |*Описание*
| matadata              | string(255)             | Имя пользователя
|===

TODO: поменять имя пользователя на абстрактную метадату, которая нужна будет по  бизнес процессу

===== Выходящие параметры
|===
|*Параметр*             |*Формат*                 |*Описание*
| id                    | int                     | Идентификатор созданого пользователя
|===

TODO: должна система хранить инфо про удаленных пользователей или должна помечать их неактивными?
Если должна хранить удаленных, тогда нужно расширение атрибутов Person, а только что созданных помечать активными.

===== Алгоритм

. Получить новый идентификатор GetNewID()
. Сохранить новый экземпляр Person
. CheckObjectByID
. Если результат предыдущего шага 1 строка, вернуть id и завершить работу, иначе вернуть ошибку.

==== Удаление пользователя

===== Входящие параметры
|===
|*Параметр*             |*Формат*             |*Описание*
| id                    | int                 | идентификатор пользователя
|===

===== Выходящие параметры

Пустой ответ - пользователь удален,
иначе - ошибка

===== Алгоритм

. CheckObjectByID - если 0 , тогда удалить, если 1 - вывести ошибку.
. После удаления вызвать CheckObjectByID, если 1 - завершить работу (вернуть пустой ответ), если 0 - тогда вернуть ошибку "Не удалось удалить пользователя {id}"

==== Создание группы пользователей

===== Входящие параметры
|===
|*Параметр*             |*Формат*                 |*Описание*
| name                  | string(255)             | Имя группы
|===

===== Выходящие параметры
|===
|*Параметр*             |*Формат*                 |*Описание*
| id                    | int                     | идентификатор группы
|===

===== Алгоритм
. Проверить что гурппа не существует, иначе вернуть ошибку "Группа с именем {name} уже существует"
. Получить новый идентификатор GetNewID()
. Сохранить новый экземпляр Group
. CheckObjectByID для только что созданной группы, если 0 (ошибок нет, объект есть в единственном экземпляре) то вернуть id) и завершить работу
. Если результат предыдущего шага 1, тогда вернуть ошибку "Не удалось создать группу {name}"

====  Изменение состава участников группы пользователей

TODO: поговорить с разработкой, возможно разнести на 2 процесса - добавление и удаление.
TODO: есть ли пользователи/процессы, которые имеют право только добавлять или только удалять?

===== Входящие параметры
|===
|*Параметр*            |*Формат*                 |*Описание*
| group_id             | int                     | идентификатор группы
a| list <structure ChangeStatusPersonInGroup>
----
1: person_id
2: operation
----
|
1: int +
2: int +
3: string ("add" , "remove")
| Идентификатор группы +
идентификатор пользователя +
дейстивие ( добавление, удаление)
|===

===== Выходящие параметры

*  статус полностью или частично удалось выполнить,
* массив ошибок при частично выполненом
* TODO: кроме массива ошибок что удобнее вывести для фиксации неуспешного результата?  id ? или логов с ошибками достаточно? кто будет править эти ошибки?


===== Алгоритм

Возможные ошибки:

* "Не удалось найти пользователя {person_id}"
* "Невозможно добавить пользователя {person_id} в группу {group_id}: пользователь уже есть в группе"
* "Невозможно удалить пользователя {person_id} из группы {group_id}: пользователя нет в группе"


. CheckObjectByID - для группы, если ошибка прекратить выполнение с ошибкой
Для каждого экземпляра `list <structure ChangeStatusPersonInGroup>`
- CheckObjectByID - для пользователя, если ошибка продолжить выполнение со следующим объектом массива, ошибку сохранить в массив ошибок

* если add  - проверить что пользователя нет в группе (иначе сохранить ошибку в массиве ошибок, продолжить выполнение со следующим экзамемпляром), добавить пользователя в группу
* если remove - проверить, что пользователь есть в группе (иначе сохранить ошибку в массиве ошибок, продолжить выполнение со следующим экзамемпляром), удалить пользователя из группы

Вернуть статус выполнения, массив ошибок

TODO: добавить недописанные фунцкии, список выше. И в задании.

