:sectnums:
:sectnumlevels: 6
:toc: left
:toclevels: 2
:toc-title: Оглавление

== Метод createPerson

Метод создания нового пользователя в системе.

=== Входные параметры

include::./createPerson/createPerson-request.adoc[]

=== Выходные параметры

include::./createPerson/createPerson-request.adoc[]

== Алгоритм работы

=== Валидация входящих параметров

|===
|*Параметр*             |*Валидация*                     |*Описание*

|1: userData.userID
1.2: userData.session

a|
1.1: NotBlank +
1.2: NotBlank +

|1: Данные о пользователе +
1.1: ID пользователя +
1.2: Cессия

|2: userName
a| 2: NotBlank
|2: Имя создаваемого пользователя

|===

=== Проверка сессии клиента

Для проверки сессии клиента вызвать серсис {} метод {} (Примечание - тут обращение к системе Авторизации и ссылка на описание нужного метода)

TODO:  добавить пример запроса методу проверки сессии клиента +
TODO:  добавить пример ответа от метода проверки сессии клиента

Примечание - это то место, где я вижу ображение к системе Авторизации с проверкой сессии полученной от третьего источника (будь это facebook или иной social service).
Любой или почти любой запрос должен начинаться с такого запроса,
если иное не согласовано с безопасностью.

=== Проверка прав пользователя getPersonPermissions

Для проверки прав пользователя вызывать getPersonPermissions с параметрами userData.userID, типы __ (id типа для ресурса таблицы пользователей), право - add
Если права нет - "Невозможно добавить пользователя {}, недостаточно прав"

=== Вызов createPersonServise

Для создания нового пользователя вызвать createPersonServise с параметром userName

=== Формирование результата

Заполнить personID параметром из createPersonServise

=== Обработка ошибок

Формирование ошибок происходит в соответствии с <<exceptions.adoc,общим правилом>>.
