:sectnums:
:sectnumlevels: 6
:toc: left
:toclevels: 2
:toc-title: Оглавление

== Метод getPersonPermissions

Для получения списка возможных операций пользователя над ресурсом необходимо вызвать сервис {serviceName-api} метод `getPersonPermissions`

=== Входные параметры

include::./getPersonPermissions-request.adoc[]

=== Выходные параметры

include::./getPersonPermissions-response.adoc[]

== Алгоритм работы

=== Валидация входящих параметров

=== Проверка сессии клиента

Для проверки сессии клиента вызвать серсис {} метод {} (Примечание - тут обращение к системе Авторизации и ссылка на описание нужного метода)

Пример запроса к ... методу
Пример ответа от ... метода

Примечание - это то место, где я вижу ображение к системе Авторизации с проверкой сессии полученной от третьего источника (будь это facebook или иной social service). Любой или почти любой запрос должен начинаться с такого запроса. Если иное не согласовано с безопасностью.

=== Проверка прав

TODO : узнать имеет ли право пользователь сам по себе получать такие данные
TODO: Надо ли закладываться, что запрос будет про другого пользователя?

=== Формирование результата

Для каждого элемента `sourse` вызвать метод `getPersonPermissionsService`.
Сформировать объект

|===
|objectID    | поле __ из сервиса getPersonPermissionsService
|objectName  | поле __ из сервиса getPersonPermissionsService
|activity    | поле __ из сервиса getPersonPermissionsService

|===

TODO: доделать возвращение имени оюъекта - objectName

=== Обработка ошибок

Формирование ошибок происходит в соответствии с <<exeptions.adoc,общим правилом>>.