:sectnums:
:sectnumlevels: 6
:toc: left
:toclevels: 2
:toc-title: Оглавление

== Метод getPersonPermissions

Для получения списка возможных операций пользователя над ресурсом необходимо вызвать сервис __ метод `getPersonPermissions`

=== Входные параметры

include::./getPersonPermissions/getPersonPermissions-request.adoc[]

=== Выходные параметры

include::./getPersonPermissions/getPersonPermissions-response.adoc[]

== Алгоритм работы

=== Валидация входящих параметров

|===
|*Параметр*             |*Проверка*                     |*Описание*

|1.1: userData.userID +
1.2: userData.session

|
  1.1 - NotBlank +
  1.2 - NotBlank
|1: Данные о пользователе +
1.1: ID пользователя +
1.2: Cессия


|2: filter
a| 2: struct SourseTypeFilter
[source, json, options="nowrap"]
----
2.1: list <int> - NotNull
----

|2: Фильтр объектов +
2.1: ID типов объектов

|===

=== Проверка сессии клиента

Для проверки сессии клиента вызвать серсис {} метод {} (Примечание - тут обращение к системе Авторизации и ссылка на описание нужного метода)

TODO:  добавить пример запроса методу проверки сессии клиента +
TODO:  добавить пример ответа от метода проверки сессии клиента

Примечание - это то место, где я вижу ображение к системе Авторизации с проверкой сессии полученной от третьего источника (будь это facebook или иной social service).
Любой или почти любой запрос должен начинаться с такого запроса,
если иное не согласовано с безопасностью.

=== Проверка прав

TODO: Узнать имеет ли право пользователь сам по себе получать такие данные
TODO: Надо ли закладываться, что запрос будет про другого пользователя?

=== Формирование результата

Для каждого элемента `SourseTypeFilter` вызвать метод `getPersonPermissionsService`.
Сформировать объект

|===
|objectID    | поле __ из сервиса getPersonPermissionsService
|objectName  | поле __ из сервиса getPersonPermissionsService
|activity    | поле __ из сервиса getPersonPermissionsService

|===

TODO: доделать возвращение имени объекта - objectName

=== Обработка ошибок

Формирование ошибок происходит в соответствии с <<exceptions.adoc,общим правилом>>.