swagger: "2.0"
info:
  description: "Это документация к тестовому заданию в Леруа Мерлен. API системы управления контролем доступа на основе ролей."
  version: "1.0.0"
  title: "Swagger"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "rogacheva.a.y@gmail.ru"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "myserver"
basePath: "/v1"
tags:
- name: "Person"
  description: "Информация о пользователях системы"
schemes:
- "https"
- "http"
paths:
  /person:
    post:
      tags:
      - "Person"
      summary: "Добавление нового пользователя в систему"
      description: "Добавление нового пользователя в систему"
      operationId: "addPerson"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Информация о пользователе и данные, которые надо добавить"
        required: true
        schema:
          $ref: "#/definitions/PersonRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/PersonResponse"
        201:
          description: "ansuccessful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
        405:
          description: "invalid input"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
  /person/{personId}:
    get:
      tags:
      - "Person"
      summary: "Получить данные пользователя по ID"
      description: "Возращает данные об одном пользователе"
      operationId: "getPersonById"
      produces:
      - "application/json"
      parameters:
      - name: "personId"
        in: "path"
        description: "ID of pet to return"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Pet object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/UserData"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/PersonResponse"
        201:
          description: "ansuccessful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Person not found"
      security:
      - api_key: []
    post:
      tags:
      - "Person"
      summary: "Обновление информации о пользователе системы"
      description: "Обновление информации о пользователе системы"
      operationId: "updatePetWithForm"
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      parameters:
      - name: "personId"
        in: "path"
        description: "ID of pet that needs to be updated"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Информация о пользователе и данные, которые надо добавить"
        required: true
        schema:
          $ref: "#/definitions/PersonRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/PersonResponse"
        201:
          description: "ansuccessful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
        405:
          description: "Invalid input"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
    delete:
      tags:
      - "Person"
      summary: "Удаление пользователя из системы"
      description: ""
      operationId: "deletePerson"
      produces:
      - "application/json"
      parameters:
      - name: "personId"
        in: "path"
        description: "ID of pet to return"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Pet object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/UserData"
      responses:
        400:
          description: "Invalid ID supplied"
        404:
          description: "Pet not found"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
  /group:
    post:
      tags:
      - "Group"
      summary: "Метод создает новую группу в системе"
      description: "Метод создает новую группу в системе"
      operationId: "addGroup"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Информация о группе и данные, которые надо добавить"
        required: true
        schema:
          $ref: "#/definitions/GroupRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/GroupResponse"
        201:
          description: "ansuccessful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
        405:
          description: "invalid input"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
    put:
      tags:
      - "Group"
      summary: "Метод добавляет пермишенов в группу"
      description: "Метод добавляет пермишенов в группу"
      operationId: "addPermissionToGroup"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Информация о группе и данные, которые надо добавить"
        required: true
        schema:
          $ref: "#/definitions/PermissionRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/PermissionResponse"
        201:
          description: "ansuccessful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
        405:
          description: "invalid input"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
    delete:
      tags:
      - "Group"
      summary: "Метод удаляет пермишены из группы"
      description: "Метод удаляет пермишены из группы"
      operationId: "deletePermissionFromGroup"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Информация о группе и данные, которые надо добавить"
        required: true
        schema:
          $ref: "#/definitions/PermissionRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/PermissionResponse"
        201:
          description: "ansuccessful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
        405:
          description: "invalid input"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
  /group/{groupId}:
    get:
      tags:
      - "Group"
      summary: "Получение данных группы по ID"
      description: "ВПолучение данных группы по ID"
      operationId: "getGroupId"
      produces:
      - "application/json"
      parameters:
      - name: "groupId"
        in: "path"
        description: "ID of pet to return"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Pet object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/UserData"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/GroupResponse"
        201:
          description: "ansuccessful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Person not found"
      security:
      - api_key: []
    delete:
      tags:
      - "Group"
      summary: "Удаление группы по ID"
      description: "Удаление группы по ID"
      operationId: "deleteGroupId"
      produces:
      - "application/json"
      parameters:
      - name: "groupId"
        in: "path"
        description: "ID of pet to return"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Pet object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/UserData"
      responses:
        200:
          description: "successful operation"
        201:
          description: "ansuccessful operation"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Person not found"
      security:
      - api_key: []
  /SourceActivities:
    post:
      tags:
      - "SourceActivities"
      summary: "Метод создает новые активности для ресурса"
      description: "Метод создает новые актиности для ресурса"
      operationId: "createSourceActivities"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Информация о группе и данные, которые надо добавить"
        required: true
        schema:
          $ref: "#/definitions/SourseRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/SourseResponse"
        201:
          description: "ansuccessful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
        405:
          description: "invalid input"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
    put:
      tags:
      - "SourceActivities"
      summary: "Метод добавляет активности для ресурса"
      description: "Метод добавляет актиности для ресурса"
      operationId: "addSourceActivities"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "groupId"
        in: "path"
        description: "ID of pet to return"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        description: "Информация о группе и данные, которые надо добавить"
        required: true
        schema:
          $ref: "#/definitions/SourseRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/SourseResponse"
        201:
          description: "ansuccessful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
        405:
          description: "invalid input"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
    delete:
      tags:
      - "SourceActivities"
      summary: "Метод удаляет новую активности для ресурса"
      description: "Метод удаляет новую активности для ресурса"
      operationId: "deleteSourceActivities"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Информация о группе и данные, которые надо добавить"
        required: true
        schema:
          $ref: "#/definitions/SourseRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/SourseResponse"
        201:
          description: "ansuccessful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
        405:
          description: "invalid input"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
  /Sourse:
    post:
      tags:
      - "Sourse"
      summary: "Метод создает новый ресурс в системе"
      description: "Метод создает новый ресурс в системе"
      operationId: "addSource"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Информация о группе и данные, которые надо добавить"
        required: true
        schema:
          $ref: "#/definitions/SourseRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/SourseResponse"
        201:
          description: "ansuccessful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
        405:
          description: "invalid input"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
  /Sourse/{SourseId}:
    get:
      tags:
      - "Sourse"
      summary: "Метод возвращает ресурс системы"
      description: "Метод возвращает ресурс системы"
      operationId: "getSource"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Информация о группе и данные, которые надо добавить"
        required: true
        schema:
          $ref: "#/definitions/UserData"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/SourseResponse"
        201:
          description: "ansuccessful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
        405:
          description: "invalid input"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"  
    delete:
      tags:
      - "Sourse"
      summary: "Удаляет ресурс"
      description: "Удаляет ресурс"
      operationId: "deleteSource"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Информация о группе и данные, которые надо добавить"
        required: true
        schema:
          $ref: "#/definitions/UserData"
      responses:
        200:
          description: "successful operation"
        201:
          description: "ansuccessful operation"
          schema:
            $ref: "#/definitions/ApiResponse"
        405:
          description: "invalid input"
      security:
      - petstore_auth:
        - "write:pets"
        - "read:pets"
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  UserData:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
      session:
        type: "string"
    xml:
      name: "UserData"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
        example: 1000
      type:
        type: "string"
        example: "BissnessError"
      message:
        type: "string"
        example: "Can't create user IvanovVV"
    xml:
      name: "ApiResponse"
  Person:
    type: "object"
    properties:
      login:
        type: "string"
        example: "IvanovVV"
    xml:
      name: "Person"
  PersonMetaData:
    type: "object"
    properties:
      surname:
        type: "string"
        example: "Ivanov"
      name:
        type: "string"
        example: "Ivan"
      department:
        type: "string"
        example: "departmentName"
      position:
        type: "string"
        example: "positionName"
    xml:
      name: "PersonMetaData"
  PersonRequest:
    type: "object"
    properties:
      userdata:
        $ref: "#/definitions/UserData"
      personBase:
        $ref: "#/definitions/Person"
      personData:
        $ref: "#/definitions/PersonMetaData"
    xml:
      name: "PersonRequest"
  PersonResponse:
    type: "object"
    properties:
      personBase:
        $ref: "#/definitions/Person"
      personData:
        $ref: "#/definitions/PersonMetaData"
      groups:
        type: array
        items: 
          $ref: "#/definitions/GroupShortData"
    xml:
      name: "PersonRequest"
  GroupShortData:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        example: "ManagersDepartmentA"
    xml:
      name: "GroupShortData"
  Group:
    type: "object"
    properties:
      name:
        type: "string"
        example: "ManagersDepartmentA"
      persons:
        type: array
        items:
          $ref: "#/definitions/Person"
      permissions:
        type: array
        items:
          $ref: "#/definitions/Permission"
    xml:
      name: "Group"
  GroupRequest:
    type: "object"
    properties:
      userdata:
        $ref: "#/definitions/UserData"
      group:
        $ref: "#/definitions/Group"
      persons:
        $ref: "#/definitions/Person"
    xml:
      name: "GroupRequest"
  GroupResponse:
    type: "object"
    properties:
      group:
        $ref: "#/definitions/Group"
      persons:
        $ref: "#/definitions/Person"
    xml:
      name: "GroupResponse"
  Permission:
    type: "object"
    properties:
      object:
        type: "string"
        example: "ObjectName"
      activities:
        type: array
        items: 
          type: "string"
          example: "create"
    xml:
      name: "Permission"
  PermissionRequest:
    type: "object"
    properties:
      userdata:
        $ref: "#/definitions/UserData"
      group:
        $ref: "#/definitions/GroupShortData"
      permissions:
        type: array
        items:
          $ref: "#/definitions/Permission"
    xml:
      name: "PermissionRequest"
  PermissionResponse:
    type: "object"
    properties:
      group:
        $ref: "#/definitions/GroupShortData"
      permissions:
        type: array
        items:
          $ref: "#/definitions/Permission"
    xml:
      name: "PermissionResponse"
  Sourse:
    type: "object"
    properties:
      name:
        type: "string"
        example: "DocumentTypeA"
    xml:
      name: "Sourse"
  SourseRequest:
    type: "object"
    properties:
      userdata:
        $ref: "#/definitions/UserData"
      sourse:
        $ref: "#/definitions/Sourse"
      permissions:
        type: array
        items:
          $ref: "#/definitions/Permission"
    xml:
      name: "SourseRequest"
  SourseResponse:
    type: "object"
    properties:
      sourse:
        $ref: "#/definitions/Sourse"
      permissions:
        type: array
        items:
          $ref: "#/definitions/Permission"
    xml:
      name: "SourseResponse"
  SourseActivitiesRequest:
    type: "object"
    properties:
      userdata:
        $ref: "#/definitions/UserData"
      sourse:
        $ref: "#/definitions/Sourse"
      permissions:
        type: array
        items:
          $ref: "#/definitions/Permission"
    xml:
      name: "SourseActivitiesRequest"
  SourseActivitiesResponse:
    type: "object"
    properties:
      userdata:
        $ref: "#/definitions/UserData"
      sourse:
        $ref: "#/definitions/Sourse"
      permissions:
        type: array
        items:
          $ref: "#/definitions/Permission"
    xml:
      name: "SourseActivitiesResponse"